# application-secret.yml
cloudflare:
  R2:
    api-token: cfut_G638ZU8CwCDLxy7ieQpw2ZYumG5FamtawZbZB2iU0c5295ad
    account-id: apalebluedot9283@sookmyung.ac.kr 
    bucket-name: YOUR_BUCKET_NAME
    public-url: https://pub-xxxxxx.r2.dev #임시 설정

openai:
  api:
    key: AQ.Ab8RN6JhmsFn8Bf___VshBgFZI7o1Iu-EKXXD_ZLHNXyrZgkww
    url: https://generativelanguage.googleapis.com/v1beta/openai/
