# application-secret.yml
cloudflare:
  api-token: cfut_G638ZU8CwCDLxy7ieQpw2ZYumG5FamtawZbZB2iU0c5295ad
  account-id: apalebluedot9283@sookmyung.ac.kr 

openai:
  api:
    key: AQ.Ab8RN6JhmsFn8Bf___VshBgFZI7o1Iu-EKXXD_ZLHNXyrZgkww
    url: https://generativelanguage.googleapis.com/v1beta/openai/
