# application-secret.yml
cloudflare:
  r2:
    account-id: ${R2_ACCOUNT_ID}
    access-key-id: ${R2_ACCESS_KEY_ID}
    secret-access-key: ${R2_SECRET_ACCESS_KEY}
    bucket-name: ${R2_BUCKET_NAME}
    endpoint: https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com
    public-url: ${R2_PUBLIC_URL}
    region: auto

openai:
  api:
    key: AQ.Ab8RN6JhmsFn8Bf___VshBgFZI7o1Iu-EKXXD_ZLHNXyrZgkww
    url: https://generativelanguage.googleapis.com/v1beta/openai/
